services:
  app:
    container_name: nodejs-service
    env_file:
      - .env
    build: 
      context: ./
    ports: 
      - ${PORT}:${PORT}
    working_dir: /app
    volumes: 
      - type: bind
        source: ./
        target: /app
    network_mode: 'host'
    depends_on:
      - postgres
    restart: always
    
    
  postgres:
    container_name: nodejs-service-db
    build: ./src/db
    volumes: 
      - nodejs-service-data:/src
    env_file:
      - .env
    networks:
      - nodejs-service
    ports: 
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always

volumes:
  nodejs-service-data:

networks:
  nodejs-service: {}
