services:
  app:
    container_name: nodejs-service
    env_file:
      - .env
    build: .
    ports: 
      - ${PORT}:${PORT}
    working_dir: /app
    volumes: 
      - type: bind
        source: ./src
        target: /app/src
    networks:
      - nodejs-service
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: nodejs-service-db
    build: ./src/db
    volumes: 
      - nodejs-service-data:/src
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_DB: '${POSTGRES_DB}'
    networks:
      - nodejs-service
    ports: 
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always

volumes:
  nodejs-service-data:

networks:
  nodejs-service: